### ISSUE TITLE
Agregar vista para todos los eventos  https://sg.com.mx/buzz/ponencias

### ISSUE THREAD

**Issue by lasr21** [softwareguru/sgbuzz#3]

**Comment by pedrogk** [comment]
Ya está la vista y el bloque para el home. 

Solo falta editar el style sheet para agregar un border y un poco de margen entre cada nota.

**Comment by lasr21** [comment]
mea culpa, mi intensión es tener una vista de eventos no de sesiones, puedas ver todos

Data day 2018
SG Virtual13,
Mobile Day 2017
etc...

**Comment by pedrogk** [comment]
Ok. Imagino que te refieres a una vista sumarizada (aggregated) donde se vea algo como:
 - SG Virtual 14 (10 sesiones)
 - Data Day 2018 (8 sesiones)
 - SG Next 2017 (4 sesiones)

donde cada item es un link a la lista de sesiones para el evento. Idealmente le ponemos unos estilos bonitos donde cada item tiene su thumbnail de imagen.
